wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.5
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1712124760.0
    t:
      1:
      - 1
      - 5
      - 9
      - 53
      - 55
      - 77
      - 103
      2:
      - 1
      - 5
      - 9
      - 53
      - 55
      - 77
      - 103
      3:
      - 7
      - 13
      - 23
      4: 3.10.13
      5: 0.16.5
      8:
      - 1
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: lr-AdamW
      5: 1
      6:
      - 1
    - 1: train/loss
      5: 1
      6:
      - 1
    - 1: train/mse
      5: 1
      6:
      - 1
    - 1: train/mae
      5: 1
      6:
      - 1
    - 1: train/r2
      5: 1
      6:
      - 1
    - 1: train/pearson_coef
      5: 1
      6:
      - 1
    - 1: train/spearman_coef
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: val/loss
      5: 1
      6:
      - 1
    - 1: val/mse
      5: 1
      6:
      - 1
    - 1: val/mae
      5: 1
      6:
      - 1
    - 1: val/r2
      5: 1
      6:
      - 1
    - 1: val/pearson_coef
      5: 1
      6:
      - 1
    - 1: val/spearman_coef
      5: 1
      6:
      - 1
node_dim:
  desc: null
  value: 9
edge_dim:
  desc: null
  value: 5
hidden_dim_graph:
  desc: null
  value: 100
hidden_dim_ffn:
  desc: null
  value: 100
num_mp_layers:
  desc: null
  value: 5
num_readout_layers:
  desc: null
  value: 2
dropout:
  desc: null
  value: 0.0
lr:
  desc: null
  value: 1.0e-05
wd:
  desc: null
  value: 0.0
aggr:
  desc: null
  value: mean
jk:
  desc: null
  value: cat
task:
  desc: null
  value: regression
pos_weight:
  desc: null
  value: 1
weight_decay:
  desc: null
  value: 0.0
out_channels:
  desc: null
  value: 1
final_relu:
  desc: null
  value: false
metric:
  desc: null
  value: val/auc
